apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: my-pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gittag
    description: The git tag
    default: latest
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: hello-git-$(uid)
    spec:
      type: git
      params:
        - name: revision
          value: $(params.gitrevision)
        - name: url
          value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: hello-pr-
    spec:
      pipelineRef:
        name: build-and-deploy-pipeline
      resources:
        - name: git-source
          resourceRef:
            name: hello-git-$(uid)
      params:
        - name: pathToYamlFile
          value: "src/tekton/basic/knative/hello.yaml"
        - name: imageUrl
          value: 192.168.56.10:5000/jouker2k/hello
        - name: imageTag
          value: $(params.gitrevision)
      serviceAccountName: pipeline-account

