apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: hello-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: hello-git-repo
  params:
    - name: pathToYamlFile
      value: "src/tekton/basic/knative/hello.yaml"
    - name: imageUrl
      value: 192.168.56.10:5000/jouker2k/hello
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline-account
