apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-git-repo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/jouker2k/devopslab
